import { LocalStore } from "../storage/localStore.js";

const KEY = "pluginSources";

function normalizeSources(input) {
  if (!Array.isArray(input)) {
    return [];
  }
  return input
    .map((source) => ({
      id: source.id || `plugin_${Math.random().toString(36).slice(2, 10)}`,
      name: String(source.name || "Custom Source").trim(),
      urlTemplate: String(source.urlTemplate || "").trim(),
      enabled: source.enabled !== false
    }))
    .filter((source) => Boolean(source.urlTemplate));
}

function applyTemplate(template, vars) {
  let output = template;
  Object.entries(vars).forEach(([key, value]) => {
    const token = `{${key}}`;
    output = output.split(token).join(String(value ?? ""));
  });
  return output;
}

export const PluginRuntime = {
  listSources() {
    return normalizeSources(LocalStore.get(KEY, []));
  },

  saveSources(sources) {
    const normalized = normalizeSources(sources);
    if (JSON.stringify(this.listSources()) === JSON.stringify(normalized)) {
      return false;
    }
    LocalStore.set(KEY, normalized);
    return true;
  },

  addSource(source) {
    const current = this.listSources();
    const normalizedUrl = String(source?.urlTemplate || "").trim();
    if (!normalizedUrl || current.some((entry) => entry.urlTemplate === normalizedUrl)) {
      return false;
    }
    current.push({ ...source, urlTemplate: normalizedUrl });
    return this.saveSources(current);
  },

  removeSource(sourceId) {
    const next = this.listSources().filter((source) => source.id !== sourceId);
    return this.saveSources(next);
  },

  setSourceEnabled(sourceId, enabled) {
    const current = this.listSources();
    const normalizedEnabled = Boolean(enabled);
    if (!current.some((source) => source.id === sourceId)) {
      return false;
    }
    if (
      current.some(
        (source) => source.id === sourceId && Boolean(source.enabled) === normalizedEnabled
      )
    ) {
      return false;
    }
    const next = current.map((source) => {
      if (source.id !== sourceId) {
        return source;
      }
      return { ...source, enabled: normalizedEnabled };
    });
    return this.saveSources(next);
  },

  execute({ tmdbId, mediaType, season = null, episode = null } = {}) {
    const vars = {
      tmdbId: tmdbId || "",
      mediaType: mediaType || "",
      season: season ?? "",
      episode: episode ?? ""
    };

    return this.listSources()
      .filter((source) => source.enabled)
      .map((source) => {
        const url = applyTemplate(source.urlTemplate, vars).trim();
        if (!url) {
          return null;
        }
        return {
          sourceId: source.id,
          sourceName: source.name,
          streams: [
            {
              name: `${source.name} Source`,
              title: `${source.name} Stream`,
              url,
              description: `Generated by template: ${source.urlTemplate}`
            }
          ]
        };
      })
      .filter(Boolean);
  }
};
