import { LocalStore } from "../storage/localStore.js";
import { ProfileManager } from "../profile/profileManager.js";

const KEY = "pluginSources";

/**
 * Repositorios de plugin sao POR PERFIL, e nao havia nada disso aqui: a lista
 * vivia num `LocalStore.get("pluginSources")` cru, ou seja, uma unica lista global
 * que todos os perfis enxergavam. Relatado por um testador -- ele ligou plugins num
 * perfil secundario e viu os repositorios do perfil principal, exatamente como
 * tinha acontecido antes com os addons.
 *
 * Um repositorio de plugin e "coisa instalada", nao preferencia: perfil novo comeca
 * VAZIO em vez de herdar o principal. (O oposto vale para tema, layout e ajustes de
 * player, que usam createProfileScopedStore e herdam de proposito.)
 *
 * MIGRACAO: uma lista antiga em formato de array pertence a quem a instalou, que so
 * pode ser o perfil principal — ela vai para o "1" e os outros perfis nascem sem
 * nada. Perfis ja contaminados nao tem como ser separados: o dado foi gravado numa
 * lista so, sem dono.
 */
function lerEnvelope() {
  const bruto = LocalStore.get(KEY, null);
  if (bruto && typeof bruto === "object" && !Array.isArray(bruto) && bruto.__profileScoped) {
    return { __profileScoped: true, profiles: { ...(bruto.profiles || {}) } };
  }
  const envelope = { __profileScoped: true, profiles: {} };
  if (Array.isArray(bruto) && bruto.length) {
    envelope.profiles["1"] = bruto;
    LocalStore.set(KEY, envelope);
  }
  return envelope;
}

function perfilAtual() {
  return String(ProfileManager.getActiveProfileId() ?? "1").trim() || "1";
}

function lerFontesDoPerfil() {
  const envelope = lerEnvelope();
  const atual = envelope.profiles[perfilAtual()];
  return Array.isArray(atual) ? atual : [];
}

function gravarFontesDoPerfil(sources) {
  const envelope = lerEnvelope();
  envelope.profiles[perfilAtual()] = Array.isArray(sources) ? sources : [];
  LocalStore.set(KEY, envelope);
}

function normalizeSources(input) {
  if (!Array.isArray(input)) {
    return [];
  }
  return input
    .map((source) => ({
      id: source.id || `plugin_${Math.random().toString(36).slice(2, 10)}`,
      name: String(source.name || "Custom Source").trim(),
      urlTemplate: String(source.urlTemplate || "").trim(),
      enabled: source.enabled !== false
    }))
    .filter((source) => Boolean(source.urlTemplate));
}

function applyTemplate(template, vars) {
  let output = template;
  Object.entries(vars).forEach(([key, value]) => {
    const token = `{${key}}`;
    output = output.split(token).join(String(value ?? ""));
  });
  return output;
}

export const PluginRuntime = {
  listSources() {
    return normalizeSources(lerFontesDoPerfil());
  },

  saveSources(sources) {
    const normalized = normalizeSources(sources);
    if (JSON.stringify(this.listSources()) === JSON.stringify(normalized)) {
      return false;
    }
    gravarFontesDoPerfil(normalized);
    return true;
  },

  addSource(source) {
    const current = this.listSources();
    const normalizedUrl = String(source?.urlTemplate || "").trim();
    if (!normalizedUrl || current.some((entry) => entry.urlTemplate === normalizedUrl)) {
      return false;
    }
    current.push({ ...source, urlTemplate: normalizedUrl });
    return this.saveSources(current);
  },

  removeSource(sourceId) {
    const next = this.listSources().filter((source) => source.id !== sourceId);
    return this.saveSources(next);
  },

  setSourceEnabled(sourceId, enabled) {
    const current = this.listSources();
    const normalizedEnabled = Boolean(enabled);
    if (!current.some((source) => source.id === sourceId)) {
      return false;
    }
    if (
      current.some(
        (source) => source.id === sourceId && Boolean(source.enabled) === normalizedEnabled
      )
    ) {
      return false;
    }
    const next = current.map((source) => {
      if (source.id !== sourceId) {
        return source;
      }
      return { ...source, enabled: normalizedEnabled };
    });
    return this.saveSources(next);
  },

  execute({ tmdbId, mediaType, season = null, episode = null } = {}) {
    const vars = {
      tmdbId: tmdbId || "",
      mediaType: mediaType || "",
      season: season ?? "",
      episode: episode ?? ""
    };

    return this.listSources()
      .filter((source) => source.enabled)
      .map((source) => {
        const url = applyTemplate(source.urlTemplate, vars).trim();
        if (!url) {
          return null;
        }
        return {
          sourceId: source.id,
          sourceName: source.name,
          streams: [
            {
              name: `${source.name} Source`,
              title: `${source.name} Stream`,
              url,
              description: `Generated by template: ${source.urlTemplate}`
            }
          ]
        };
      })
      .filter(Boolean);
  }
};
